INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(1, 'bardo', '0', 'Ataque Certeiro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(2, 'bardo', '0', 'Consertar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(3, 'bardo', '0', 'Globo de Luz');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(4, 'bardo', '0', 'Ilusão Menor');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(5, 'bardo', '0', 'Mãos Mágicas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(6, 'bardo', '0', 'Mensagem');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(7, 'bardo', '0', 'Prestidigitação');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(8, 'bardo', '0', 'Proteção Contra Lâminas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(9, 'bardo', '0', 'Zombaria Viciosa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(10, 'bruxo', '0', 'Ataque Certeiro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(11, 'bruxo', '0', 'Ilusão Menor');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(12, 'bruxo', '0', 'Mãos Mágicas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(13, 'bruxo', '0', 'Prestidigitação');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(14, 'bruxo', '0', 'Proteção Contra Lâminas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(15, 'bruxo', '0', 'Rajada Mística');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(16, 'bruxo', '0', 'Rajada de Veneno');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(17, 'bruxo', '0', 'Toque Arrepiante');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(18, 'clerigo', '0', 'Consertar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(19, 'clerigo', '0', 'Estabilizar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(20, 'clerigo', '0', 'Luz');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(21, 'clerigo', '0', 'Orientação');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(22, 'clerigo', '0', 'Resistência');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(23, 'clerigo', '0', 'Taumaturgia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(24, 'druida', '0', 'Chicote de Espinhos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(25, 'druida', '0', 'Consertar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(26, 'druida', '0', 'Criar Chamas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(27, 'druida', '0', 'Drudismo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(28, 'druida', '0', 'Orientação');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(29, 'druida', '0', 'Rajada de Veneno');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(30, 'druida', '0', 'Resistência');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(31, 'druida', '0', 'Consertar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(32, 'feiticeiro', '0', 'Ataque Certeiro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(33, 'feiticeiro', '0', 'Consertar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(34, 'feiticeiro', '0', 'Espirro Ácido');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(35, 'feiticeiro', '0', 'Globo de Luz');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(36, 'feiticeiro', '0', 'Ilusão Menor');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(37, 'feiticeiro', '0', 'Luz');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(38, 'feiticeiro', '0', 'Mãos Mágicas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(39, 'feiticeiro', '0', 'Mensagem');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(40, 'feiticeiro', '0', 'Raio de Fogo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(41, 'feiticeiro', '0', 'Radio de Gelo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(42, 'Feiticeiro', '0', 'Proteção Contra Lâminas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(43, 'mago', '0', 'Ataque Certeiro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(44, 'mago', '0', 'Consertar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(45, 'mago', '0', 'Espirro Ácido');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(46, 'mago', '0', 'Globos de Luz');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(47, 'mago', '0', 'Ilusão Menor');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(48, 'mago', '0', 'Luz');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(49, 'mago', '0', 'Mãos Mágicas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(50, 'mago', '0', 'Mensagem');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(51, 'mago', '0', 'Prestidigitação');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(52, 'mago', '0', 'Proteção contra Lâminas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(53, 'mago', '0', 'Raio de Fogo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(54, 'mago', '0', 'Raio de Gelo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(55, 'mago', '0', 'Rajada de Veneno');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(56, 'mago', '0', 'Toque Arrepiante');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(57, 'mago', '0', 'Toque Chocante');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(58, 'bardo', '1', 'Amizade Animal');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(59, 'bardo', '1', 'Compreender Idiomas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(60, 'bardo', '1', 'Curar Ferimentos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(61, 'bardo', '1', 'Detectar Magia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(62, 'bardo', '1', 'Disfarçar-se');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(63, 'bardo', '1', 'Escrita Ilusória');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(64, 'bardo', '1', 'Falar com Animais');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(65, 'bardo', '1', 'Falar com Plantas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(66, 'bardo', '1', 'Fogo das Fadas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(67, 'bardo', '1', 'Heroísmo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(68, 'bardo', '1', 'Identificação');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(69, 'bardo', '1', 'Imagem Silenciosa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(70, 'bruxo', '1', 'Armadura de Agathys');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(71, 'bruxo', '1', 'Braços de Hadar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(72, 'bruxo', '1', 'Bruxaria');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(73, 'bruxo', '1', 'Compreender Idiomas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(74, 'bruxo', '1', 'Enfeitiçar Pessoa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(75, 'bruxo', '1', 'Escrita Ilusória');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(76, 'bruxo', '1', 'Proteção contra o Bem e Mal');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(77, 'bruxo', '1', 'Raio de Bruxa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(78, 'bruxo', '1', 'Recuo Acelerado');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(79, 'bruxo', '1', 'Repreensão Infernal');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(80, 'clerigo', '1', 'Benção');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(81, 'clerigo', '1', 'Comando');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(82, 'clerigo', '1', 'Criar ou Destruir Água');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(83, 'clerigo', '1', 'Curar Ferimentos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(84, 'clerigo', '1', 'Detectar o Bem e Mal');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(85, 'clerigo', '1', 'Detectar Magia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(86, 'clerigo', '1', 'Detectar Veneno e Doença');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(87, 'clerigo', '1', 'Escudo da Fé');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(88, 'clerigo', '1', 'Infligir Ferimentos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(89, 'clerigo', '1', 'Palavra Curativa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(90, 'clerigo', '1', 'Perdição');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(91, 'clerigo', '1', 'Proteção contra o Bem e Mal');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(92, 'clerigo', '1', 'Purificar Alimentos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(93, 'clerigo', '1', 'Raio Guiador');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(94, 'clerigo', '1', 'Santuario');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(95, 'druida', '1', 'Amizade Animal');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(96, 'druida', '1', 'Bom Fruto');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(97, 'druida', '1', 'Curar Ferimentos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(98, 'druida', '1', 'Constrição');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(99, 'druida', '1', 'Criar ou Destruir Água');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(100, 'druida', '1', 'Detectar Magia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(101, 'druida', '1', 'Detectar Veneno e Doença');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(102, 'druida', '1', 'Enfeitiçar Pessoa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(103, 'druida', '1', 'Falar com Animais');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(104, 'druida', '1', 'Falar com Plantas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(105, 'druida', '1', 'Fogo das Fadas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(106, 'druida', '1', 'Névoa Obscurecente');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(107, 'druida', '1', 'Palavra Curativa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(108, 'druida', '1', 'Passos Longos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(109, 'druida', '1', 'Purificar Alimentos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(110, 'druida', '1', 'Salto');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(111, 'feiticeiro', '1', 'Armadura Arcana');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(112, 'feiticeiro', '1', 'Compreender Idiomas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(113, 'feiticeiro', '1', 'Detectar Magia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(114, 'feiticeiro', '1', 'Disfarçar-se');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(115, 'feiticeiro', '1', 'Enfeitiçar Pessoa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(116, 'feiticeiro', '1', 'Escudo Arcano');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(117, 'feiticeiro', '1', 'Imagem Silenciosa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(118, 'feiticeiro', '1', 'Leque Cromático');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(119, 'feiticeiro', '1', 'Mãos Flamejantes');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(120, 'feiticeiro', '1', 'Mísseis Mágicos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(121, 'feiticeiro', '1', 'Névoa Obscurecente');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(122, 'feiticeiro', '1', 'Onda Trovejante');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(123, 'feiticeiro', '1', 'Orbe Cromática');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(124, 'feiticeiro', '1', 'Queda Suave');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(125, 'feiticeiro', '1', 'Raio Adoecente');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(126, 'feiticeiro', '1', 'Raio de Bruxa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(127, 'feiticeiro', '1', 'Recuo Acelerado');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(128, 'feiticeiro', '1', 'Salto');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(129, 'feiticeiro', '1', 'Sono');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(130, 'feiticeiro', '1', 'Vitalidade Falsa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(131, 'mago', '1', 'Alarme');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(132, 'mago', '1', 'Área Escorregadia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(133, 'mago', '1', 'Armadura Arcana');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(134, 'mago', '1', 'Compreender Idiomas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(135, 'mago', '1', 'Detectar Magia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(136, 'mago', '1', 'Escudo Arcano');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(137, 'mago', '1', 'Convocar Familiar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(138, 'mago', '1', 'Disco Flutuante de Tenser');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(139, 'mago', '1', 'Disfarçar-se');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(140, 'mago', '1', 'Escrita Ilusória');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(141, 'mago', '1', 'Enfeitiçar Pessoa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(142, 'mago', '1', 'Identificação');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(143, 'mago', '1', 'Imagem Silenciosa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(144, 'mago', '1', 'Leque Cromático');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(145, 'mago', '1', 'Mãos Flamejantes');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(146, 'mago', '1', 'Mísseis Mágicos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(147, 'mago', '1', 'Mãos Flamejantes');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(148, 'mago', '1', 'Névoa Obscurecente');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(149, 'mago', '1', 'Onda Trovejante');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(150, 'mago', '1', 'Orbe Cromática');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(151, 'mago', '1', 'Passos Longos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(152, 'mago', '1', 'Proteção contra o Bem e Mal');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(153, 'mago', '1', 'Raio Adoecente');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(154, 'mago', '1', 'Queda Suave');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(155, 'mago', '1', 'Raio de Bruxa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(156, 'mago', '1', 'Recuo Acelerado');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(157, 'mago', '1', 'Riso Histérico de Tasha');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(158, 'mago', '1', 'Salto');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(159, 'mago', '1', 'Servo Invisível');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(160, 'mago', '1', 'Sono');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(161, 'mago', '1', 'Vitalidade Falsa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(162, 'bardo', '2', 'Acalmar Emoções');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(163, 'bardo', '2', 'Aprimorar Habilidade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(164, 'bardo', '2', 'Arrombar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(165, 'bardo', '2', 'Boca Encantada');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(166, 'bardo', '2', 'Cativar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(167, 'bardo', '2', 'Cegueira/Surdez');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(168, 'bardo', '2', 'Coroa da Loucura');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(169, 'bardo', '2', 'Detectar Pensamentos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(170, 'bardo', '2', 'Despedaçar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(171, 'bardo', '2', 'Esquentar Metal');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(172, 'bardo', '2', 'Imobilizar Pessoa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(173, 'bardo', '2', 'Invisibilidade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(174, 'bardo', '2', 'Restauração Menor');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(175, 'bardo', '2', 'Força Fantasmagórica');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(176, 'bardo', '2', 'Localizar Animais ou Plantas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(177, 'bardo', '2', 'Localizar Objeto');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(178, 'bardo', '2', 'Nuvem de Adagas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(179, 'bardo', '2', 'Mensageiro Animal');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(180, 'bardo', '2', 'Silêncio');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(181, 'bardo', '2', 'Ver o Invisível');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(182, 'bardo', '2', 'Zona da Verdade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(183, 'bardo', '3', 'Ampliar Plantas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(184, 'bardo', '3', 'Clarividência');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(185, 'bardo', '3', 'Dificultar Detecção');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(186, 'bardo', '3', 'Dissipar Magia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(187, 'bardo', '3', 'Enviar Mensagem');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(188, 'bardo', '3', 'Falar com Os Mortos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(189, 'bardo', '3', 'Forjar Morte');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(190, 'bardo', '3', 'Glifo de Vigilância');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(191, 'bardo', '3', 'Idiomas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(192, 'bardo', '3', 'Imagem Maior');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(193, 'bardo', '3', 'Medo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(194, 'bardo', '3', 'Névoa Fétida');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(195, 'bardo', '3', 'Padrão Hipnótico');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(196, 'bardo', '3', 'Palavra Curativa Em Massa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(197, 'bardo', '3', 'Pequena Cabana de Leomund');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(198, 'bardo', '3', 'Rogar Maldição');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(199, 'bardo', '4', 'Compulsão');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(200, 'bardo', '4', 'Confusão');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(201, 'bardo', '4', 'Invisibilidade Maior');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(202, 'bardo', '4', 'Localizar Criatura');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(203, 'bardo', '4', 'Movimentação Livre');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(204, 'bardo', '4', 'Metamorfose');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(205, 'bardo', '4', 'Porta Dimensional');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(206, 'bardo', '4', 'Terreno Alucinógeno');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(207, 'bardo', '5', 'Âncora Planar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(208, 'bardo', '5', 'Animar Objetos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(209, 'bardo', '5', 'Despistar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(210, 'bardo', '5', 'Imobilizar Monstro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(211, 'bardo', '5', 'Círculo de Teletransporte');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(212, 'bardo', '5', 'Conhecimento Lendário');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(213, 'bardo', '5', 'Despertar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(214, 'bardo', '5', 'Dominar Pessoa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(215, 'bardo', '5', 'Missão');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(216, 'bardo', '5', 'Restauração Maior');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(217, 'bardo', '5', 'Modificar Memória');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(218, 'bardo', '5', 'Reviver os Mortos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(219, 'bardo', '5', 'Similaridade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(220, 'bardo', '5', 'Sonho');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(221, 'bardo', '5', 'Vidência');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(222, 'bardo', '6', 'Ataque Visual');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(223, 'bardo', '6', 'Dança Irresistível de Otto');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(224, 'bardo', '6', 'Encontrar o Caminho');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(225, 'bardo', '6', 'Ilusão Programada');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(226, 'bardo', '6', 'Visão da Verdade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(227, 'bardo', '6', 'Proteger Fortaleza');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(229, 'bardo', '6', 'Sugestão Em Massa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(230, 'bardo', '7', 'Espada de Mordenkainen');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(231, 'bardo', '7', 'Mansão Magnífica de Mordenkainen');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(232, 'bardo', '7', 'Regeneração');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(233, 'bardo', '7', 'Forma Etérea');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(234, 'bardo', '7', 'Miragem');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(235, 'bardo', '7', 'Prisão de Energia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(236, 'bardo', '7', 'Projetar Imagem');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(237, 'bardo', '7', 'Teletransporte');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(238, 'bardo', '7', 'Ressurreição');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(239, 'bardo', '7', 'Símbolo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(240, 'bardo', '8', 'Dominar Monstro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(241, 'bardo', '8', 'Enfraquecer Intelecto');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(242, 'bardo', '8', 'Limpar a Mente');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(243, 'bardo', '8', 'Loquacidade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(244, 'bardo', '8', 'Palavra de Poder Atordoar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(245, 'bardo', '9', 'Metamorfose Verdadeira');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(246, 'bardo', '9', 'Palavra de Poder Curar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(247, 'bardo', '9', 'Palavra de Poder Matar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(248, 'bardo', '9', 'Sexto Sentido');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(249, 'bruxo', '2', 'Cativar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(250, 'bruxo', '2', 'Coroa da Loucura');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(251, 'bruxo', '2', 'Despedaçar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(252, 'bruxo', '2', 'Escuridão');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(253, 'bruxo', '2', 'Imobilizar Pessoa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(254, 'bruxo', '2', 'Invisibilidade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(255, 'bruxo', '2', 'Nuvem de Adagas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(256, 'bruxo', '2', 'Passo Nebuloso');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(257, 'bruxo', '2', 'Patas de Aranha');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(258, 'bruxo', '2', 'Raio do Enfraquecimento');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(259, 'bruxo', '2', 'Reflexos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(260, 'bruxo', '2', 'Sugestão');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(261, 'bruxo', '3', 'Contramágica');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(262, 'bruxo', '3', 'Dissipar Magia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(263, 'bruxo', '3', 'Idiomas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(264, 'bruxo', '3', 'Fome de Hadar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(265, 'bruxo', '3', 'Forma Gasosa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(266, 'bruxo', '3', 'Imagem Maior');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(267, 'bruxo', '3', 'Medo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(268, 'bruxo', '3', 'Padrão Hipnótico');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(269, 'bruxo', '3', 'Remover Maldição');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(270, 'bruxo', '3', 'Toque Vampírico');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(271, 'bruxo', '3', 'Voo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(272, 'bruxo', '4', 'Banimento');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(273, 'bruxo', '4', 'Malogro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(274, 'bruxo', '4', 'Porta Dimensional');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(275, 'bruxo', '4', 'Terreno Alucinógeno');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(276, 'bruxo', '4', 'Imobilizar Monstro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(277, 'bruxo', '5', 'Contato Extraplanar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(278, 'bruxo', '5', 'Sonho');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(279, 'bruxo', '5', 'Vidência');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(280, 'bruxo', '6', 'Ataque Visual');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(281, 'bruxo', '6', 'Carne Para Pedra');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(282, 'bruxo', '6', 'Círculo da Morte');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(283, 'bruxo', '6', 'Visão da Verdade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(284, 'bruxo', '6', 'Conjurar Fada');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(285, 'bruxo', '6', 'Criar Mortos-Vivos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(286, 'bruxo', '6', 'Portal Arcano');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(287, 'bruxo', '6', 'Sugestão Em Massa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(288, 'bruxo', '7', 'Dedo da Morte');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(289, 'bruxo', '7', 'Forma Etérea');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(290, 'bruxo', '7', 'Prisão de Energia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(291, 'bruxo', '7', 'Viagem Planar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(292, 'bruxo', '8', 'Dominar Monstro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(293, 'bruxo', '8', 'Enfraquecer Intelecto');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(294, 'bruxo', '8', 'Loquacidade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(295, 'bruxo', '8', 'Palavra de Poder Atordoar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(296, 'bruxo', '8', 'Semiplano');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(297, 'bruxo', '9', 'Aprisionamento');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(298, 'bruxo', '9', 'Palavra de Poder Matar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(299, 'bruxo', '9', 'Sexto Sentido');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(300, 'bruxo', '9', 'Metamorfose Verdadeira');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(301, 'bruxo', '9', 'Projeção Astral');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(302, 'clerigo', '2', 'Acalmar Emoções');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(303, 'clerigo', '2', 'Ajuda');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(304, 'clerigo', '2', 'Aprimorar Habilidade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(305, 'clerigo', '2', 'Arma Espiritual');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(306, 'clerigo', '2', 'Augúrio');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(307, 'clerigo', '2', 'Cegueira/Surdez');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(308, 'clerigo', '2', 'Chama Contínua');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(309, 'clerigo', '2', 'Oração Curativa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(310, 'clerigo', '2', 'Proteção contra Veneno');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(311, 'clerigo', '2', 'Encontrar Armadilhas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(312, 'clerigo', '2', 'Imobilizar Pessoa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(313, 'clerigo', '2', 'Localizar Objeto');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(314, 'clerigo', '2', 'Repouso Tranquilo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(315, 'clerigo', '2', 'Restauração Menor');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(316, 'clerigo', '2', 'Silêncio');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(317, 'clerigo', '2', 'Vínculo Protetor');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(318, 'clerigo', '2', 'Zona da Verdade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(319, 'clerigo', '3', 'Andar Na Água');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(320, 'clerigo', '3', 'Animar Mortos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(321, 'clerigo', '3', 'Círculo Mágico');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(322, 'clerigo', '3', 'Clarividência');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(323, 'clerigo', '3', 'Dissipar Magia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(324, 'clerigo', '3', 'Enviar Mensagem');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(325, 'clerigo', '3', 'Espíritos Guardiões');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(326, 'clerigo', '3', 'Idiomas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(327, 'clerigo', '3', 'Falar com Os Mortos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(328, 'clerigo', '3', 'Forjar Morte');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(329, 'clerigo', '3', 'Glifo de Vigilância');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(330, 'clerigo', '3', 'Luz do Dia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(331, 'clerigo', '3', 'Mesclar-se Às Rochas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(332, 'clerigo', '3', 'Palavra Curativa Em Massa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(333, 'clerigo', '3', 'Proteção contra Energia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(334, 'clerigo', '3', 'Remover Maldição');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(335, 'clerigo', '3', 'Revivificar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(336, 'clerigo', '3', 'Rogar Maldição');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(337, 'clerigo', '3', 'Sinal de Esperança');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(338, 'clerigo', '4', 'Adivinhação');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(339, 'clerigo', '4', 'Banimento');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(340, 'clerigo', '4', 'Guardião da Fé');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(341, 'clerigo', '4', 'Localizar Criatura');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(342, 'clerigo', '4', 'Movimentação Livre');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(343, 'clerigo', '4', 'Controlar a Água');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(344, 'clerigo', '4', 'Moldar Rochas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(345, 'clerigo', '4', 'Proteção contra a Morte');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(346, 'clerigo', '5', 'Âncora Planar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(347, 'clerigo', '5', 'Coluna de Chamas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(348, 'clerigo', '5', 'Curar Ferimentos Em Massa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(349, 'clerigo', '5', 'Comunhão');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(350, 'clerigo', '5', 'Conhecimento Lendário');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(351, 'clerigo', '5', 'Consagrar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(352, 'clerigo', '5', 'Dissipar o Bem e Mal');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(353, 'clerigo', '5', 'Missão');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(354, 'clerigo', '5', 'Praga');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(355, 'clerigo', '5', 'Praga de Insetos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(356, 'clerigo', '5', 'Restauração Maior');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(357, 'clerigo', '5', 'Vidência');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(358, 'clerigo', '5', 'Reviver Os Mortos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(359, 'clerigo', '6', 'Aliado Planar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(360, 'clerigo', '6', 'Banquete dos Heróis');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(361, 'clerigo', '6', 'Barreira de Lâminas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(362, 'clerigo', '6', 'Cura Completa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(363, 'clerigo', '6', 'Doença Plena');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(364, 'clerigo', '6', 'Encontrar o Caminho');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(365, 'clerigo', '6', 'Palavra de Recordação');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(366, 'clerigo', '6', 'Criar Mortos-Vivos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(367, 'clerigo', '6', 'Proibição');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(368, 'clerigo', '6', 'Visão da Verdade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(369, 'clerigo', '7', 'Conjurar Celestial');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(370, 'clerigo', '7', 'Forma Etérea');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(371, 'clerigo', '7', 'Palavra Divina');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(372, 'clerigo', '7', 'Regeneração');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(373, 'clerigo', '7', 'Ressurreição');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(374, 'clerigo', '7', 'Símbolo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(375, 'clerigo', '7', 'Tempestade de Fogo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(376, 'clerigo', '7', 'Viagem Planar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(377, 'clerigo', '8', 'Aura Sagrada');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(378, 'clerigo', '8', 'Campo Antimagia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(379, 'clerigo', '8', 'Controlar o Clima');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(380, 'clerigo', '8', 'Terremoto');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(381, 'clerigo', '9', 'Cura Completa Em Massa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(382, 'clerigo', '9', 'Portal');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(383, 'clerigo', '9', 'Ressurreição Verdadeira');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(384, 'clerigo', '9', 'Projeção Astral');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(385, 'druida', '2', 'Aprimorar Habilidade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(386, 'druida', '2', 'Crescer Espinhos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(387, 'druida', '2', 'Encontrar Armadilhas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(388, 'druida', '2', 'Esfera Flamejante');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(389, 'druida', '2', 'Esquentar Metal');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(390, 'druida', '2', 'Localizar Animais ou Plantas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(391, 'druida', '2', 'Imobilizar Pessoa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(392, 'druida', '2', 'Lâmina Flamejante');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(393, 'druida', '2', 'Localizar Objeto');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(394, 'druida', '2', 'Lufada de Vento');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(395, 'druida', '2', 'Mensageiro Animal');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(396, 'druida', '2', 'Passos Sem Pegadas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(397, 'druida', '2', 'Pele de Árvore');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(398, 'druida', '2', 'Proteção contra Veneno');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(399, 'druida', '2', 'Restauração Menor');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(400, 'druida', '2', 'Visão No Escuro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(401, 'druida', '2', 'Raio Lunar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(402, 'druida', '2', 'Sentido Bestial');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(403, 'druida', '3', 'Ampliar Plantas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(404, 'druida', '3', 'Andar Na Água');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(405, 'druida', '3', 'Conjurar Animais');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(406, 'druida', '3', 'Convocar Relâmpagos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(407, 'druida', '3', 'Dissipar Magia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(408, 'druida', '3', 'Forjar Morte');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(409, 'druida', '3', 'Luz do Dia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(410, 'druida', '3', 'Mesclar-se Às Rochas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(411, 'druida', '3', 'Muralha de Vento');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(412, 'druida', '3', 'Nevasca');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(413, 'druida', '3', 'Proteção contra Energia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(414, 'druida', '3', 'Respirar Na Água');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(415, 'druida', '4', 'Confusão');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(416, 'druida', '4', 'Conjurar Elementais Menores');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(417, 'druida', '4', 'Conjurar Seres da Floresta');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(418, 'druida', '4', 'Controlar a Água');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(419, 'druida', '4', 'Dominar Besta');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(420, 'druida', '4', 'Inseto Gigante');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(421, 'druida', '4', 'Malogro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(422, 'druida', '4', 'Localizar Criatura');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(423, 'druida', '4', 'Metamorfose');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(424, 'druida', '4', 'Moldar Rochas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(425, 'druida', '4', 'Movimentação Livre');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(426, 'druida', '4', 'Muralha de Fogo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(427, 'druida', '4', 'Pele de Pedra');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(428, 'druida', '4', 'Tempestade de Gelo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(429, 'druida', '4', 'Terreno Alucinógeno');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(430, 'druida', '4', 'Vinha Esmagadora');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(431, 'druida', '5', 'Âncora Planar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(432, 'druida', '5', 'Caminhar Em Árvores');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(433, 'druida', '5', 'Comunhão com a Natureza');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(434, 'druida', '5', 'Conjurar Elemental');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(435, 'druida', '5', 'Cúpula Antivida');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(436, 'druida', '5', 'Curar Ferimentos Em Massa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(437, 'druida', '5', 'Despertar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(438, 'druida', '5', 'Missão');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(439, 'druida', '5', 'Muralha de Pedra');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(440, 'druida', '5', 'Praga');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(441, 'druida', '5', 'Praga de Insetos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(442, 'druida', '5', 'Reencarnação');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(443, 'druida', '5', 'Restauração Maior');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(444, 'druida', '5', 'Vidência');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(445, 'druida', '6', 'Banquete dos Heróis');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(446, 'druida', '6', 'Caminhar No Vento');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(447, 'druida', '6', 'Cura Completa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(448, 'druida', '6', 'Conjurar Fada');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(449, 'druida', '6', 'Encontrar o Caminho');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(450, 'druida', '6', 'Mover Terra');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(451, 'druida', '6', 'Muralha de Espinhos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(452, 'druida', '6', 'Raio Solar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(453, 'druida', '6', 'Teletransporte Por Árvores');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(454, 'druida', '7', 'Inverter a Gravidade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(455, 'druida', '7', 'Miragem');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(456, 'druida', '7', 'Regeneração');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(457, 'druida', '7', 'Tempestade de Fogo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(458, 'druida', '7', 'Viagem Planar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(459, 'druida', '8', 'Antipatia/Simpatia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(460, 'druida', '8', 'Controlar o Clima');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(461, 'druida', '8', 'Enfraquecer Intelecto');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(462, 'druida', '8', 'Explosão Solar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(463, 'druida', '8', 'Formas Animais');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(464, 'druida', '8', 'Terremoto');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(465, 'druida', '8', 'Tsunami');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(466, 'druida', '9', 'Alterar Forma');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(467, 'druida', '9', 'Ressurreição Verdadeira');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(468, 'druida', '9', 'Sexto Sentido');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(469, 'druida', '9', 'Tempestade da Vingança');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(470, 'feiticeiro', '2', 'Alterar-se');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(471, 'feiticeiro', '2', 'Aprimorar Habilidade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(472, 'feiticeiro', '2', 'Arrombar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(473, 'feiticeiro', '2', 'Aumentar/Reduzir');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(474, 'feiticeiro', '2', 'Cegueira/Surdez');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(475, 'feiticeiro', '2', 'Coroa da Loucura');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(476, 'feiticeiro', '2', 'Despedaçar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(477, 'feiticeiro', '2', 'Detectar Pensamentos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(478, 'feiticeiro', '2', 'Escuridão');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(479, 'feiticeiro', '2', 'Imobilizar Pessoa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(480, 'feiticeiro', '2', 'Invisibilidade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(481, 'feiticeiro', '2', 'Força Fantasmagórica');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(482, 'feiticeiro', '2', 'Passo Nebuloso');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(483, 'feiticeiro', '2', 'Levitação');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(484, 'feiticeiro', '2', 'Lufada de Vento');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(485, 'feiticeiro', '2', 'Nublar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(486, 'feiticeiro', '2', 'Nuvem de Adagas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(487, 'feiticeiro', '2', 'Patas de Aranha');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(488, 'feiticeiro', '2', 'Raio Ardente');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(489, 'feiticeiro', '2', 'Ver o Invisível');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(490, 'feiticeiro', '2', 'Raio Ardente');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(491, 'feiticeiro', '2', 'Reflexos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(492, 'feiticeiro', '2', 'Sugestão');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(493, 'feiticeiro', '2', 'Teia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(494, 'feiticeiro', '2', 'Visão No Escuro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(495, 'feiticeiro', '3', 'Andar Na Água');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(496, 'feiticeiro', '3', 'Bola de Fogo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(497, 'feiticeiro', '3', 'Clarividência');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(498, 'feiticeiro', '3', 'Contramágica');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(499, 'feiticeiro', '3', 'Dissipar Magia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(500, 'feiticeiro', '3', 'Idiomas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(501, 'feiticeiro', '3', 'Imagem Maior');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(502, 'feiticeiro', '3', 'Forma Gasosa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(503, 'feiticeiro', '3', 'Lentidão');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(504, 'feiticeiro', '3', 'Luz do Dia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(505, 'feiticeiro', '3', 'Medo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(506, 'feiticeiro', '3', 'Proteção contra Energia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(507, 'feiticeiro', '3', 'Nevasca');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(508, 'feiticeiro', '3', 'Névoa Fétida');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(509, 'feiticeiro', '3', 'Padrão Hipnótico');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(510, 'feiticeiro', '3', 'Piscar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(511, 'feiticeiro', '3', 'Relâmpago');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(512, 'feiticeiro', '3', 'Respirar Na Água');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(513, 'feiticeiro', '3', 'Velocidade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(514, 'feiticeiro', '3', 'Voo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(515, 'feiticeiro', '4', 'Banimento');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(516, 'feiticeiro', '4', 'Confusão');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(517, 'feiticeiro', '4', 'Dominar Besta');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(518, 'feiticeiro', '4', 'Invisibilidade Maior');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(519, 'feiticeiro', '4', 'Malogro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(520, 'feiticeiro', '4', 'Metamorfose');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(521, 'feiticeiro', '4', 'Muralha de Fogo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(522, 'feiticeiro', '4', 'Pele de Pedra');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(523, 'feiticeiro', '4', 'Porta Dimensional');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(524, 'feiticeiro', '4', 'Tempestade de Gelo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(525, 'feiticeiro', '5', 'Animar Objetos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(526, 'feiticeiro', '5', 'Círculo de Teletransporte');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(527, 'feiticeiro', '5', 'Cone de Frio');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(528, 'feiticeiro', '5', 'Criação');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(529, 'feiticeiro', '5', 'Imobilizar Monstro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(530, 'feiticeiro', '5', 'Dominar Pessoa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(531, 'feiticeiro', '5', 'Muralha de Pedra');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(532, 'feiticeiro', '5', 'Névoa Mortal');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(533, 'feiticeiro', '5', 'Praga de Insetos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(534, 'feiticeiro', '5', 'Similaridade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(535, 'feiticeiro', '5', 'Telecinésia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(536, 'feiticeiro', '6', 'Ataque Visual');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(537, 'feiticeiro', '6', 'Banquete dos Heróis');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(538, 'feiticeiro', '6', 'Círculo da Morte');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(539, 'feiticeiro', '6', 'Corrente de Relâmpagos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(540, 'feiticeiro', '6', 'Desintegrar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(541, 'feiticeiro', '6', 'Visão da Verdade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(542, 'feiticeiro', '6', 'Globo de Invulnerabilidade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(543, 'feiticeiro', '6', 'Mover Terra');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(544, 'feiticeiro', '6', 'Portal Arcano');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(545, 'feiticeiro', '6', 'Raio Solar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(546, 'feiticeiro', '6', 'Sugestão Em Massa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(547, 'feiticeiro', '7', 'Bola de Fogo Controlável');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(548, 'feiticeiro', '7', 'Dedo da Morte');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(549, 'feiticeiro', '7', 'Forma Etérea');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(550, 'feiticeiro', '7', 'Inverter a Gravidade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(551, 'feiticeiro', '7', 'Tempestade de Fogo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(552, 'feiticeiro', '7', 'Teletransporte');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(553, 'feiticeiro', '7', 'Rajada Prismática');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(554, 'feiticeiro', '7', 'Viagem Planar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(555, 'feiticeiro', '8', 'Dominar Monstro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(556, 'feiticeiro', '8', 'Explosão Solar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(557, 'feiticeiro', '8', 'Nuvem Incendiária');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(558, 'feiticeiro', '8', 'Palavra de Poder Atordoar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(559, 'feiticeiro', '8', 'Terremoto');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(560, 'feiticeiro', '9', 'Chuva de Meteoros');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(561, 'feiticeiro', '9', 'Palavra de Poder Matar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(562, 'feiticeiro', '9', 'Parar o Tempo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(563, 'feiticeiro', '9', 'Desejo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(564, 'feiticeiro', '9', 'Portal');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(565, 'mago', '2', 'Alterar-se');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(566, 'mago', '2', 'Alterar-se');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(567, 'mago', '2', 'Arrombar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(568, 'mago', '2', 'Aumentar/Reduzir');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(569, 'mago', '2', 'Aura Mágica de Nystul');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(570, 'mago', '2', 'Boca Encantada');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(571, 'mago', '2', 'Cegueira/Surdez');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(572, 'mago', '2', 'Chama Contínua');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(573, 'mago', '2', 'Coroa da Loucura');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(574, 'mago', '2', 'Despedaçar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(575, 'mago', '2', 'Detectar Pensamentos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(576, 'mago', '2', 'Escuridão');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(577, 'mago', '2', 'Flecha Ácida de Melf');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(578, 'mago', '2', 'Esfera Flamejante');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(579, 'mago', '2', 'Força Fantasmagórica');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(580, 'mago', '2', 'Imobilizar Pessoa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(581, 'mago', '2', 'Invisibilidade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(582, 'mago', '2', 'Levitação');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(583, 'mago', '2', 'Localizar Objeto');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(584, 'mago', '2', 'Nublar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(585, 'mago', '2', 'Passo Nebuloso');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(586, 'mago', '2', 'Nuvem de Adagas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(587, 'mago', '2', 'Lufada de Vento');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(588, 'mago', '2', 'Patas de Aranha');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(589, 'mago', '2', 'Raio Ardente');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(590, 'mago', '2', 'Raio do Enfraquecimento');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(591, 'mago', '2', 'Reflexos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(592, 'mago', '2', 'Repouso Tranquilo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(593, 'mago', '2', 'Sugestão');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(594, 'mago', '2', 'Tranca Arcana');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(595, 'mago', '2', 'Teia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(596, 'mago', '2', 'Truque de Corda');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(597, 'mago', '2', 'Ver o Invisível');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(598, 'mago', '2', 'Visão No Escuro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(599, 'mago', '3', 'Animar Mortos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(600, 'mago', '3', 'Bola de Fogo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(601, 'mago', '3', 'Clarividência');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(602, 'mago', '3', 'Círculo Mágico');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(603, 'mago', '3', 'Contramágica');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(604, 'mago', '3', 'Dificultar Detecção');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(605, 'mago', '3', 'Dissipar Magia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(606, 'mago', '3', 'Enviar Mensagem');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(607, 'mago', '3', 'Forjar Morte');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(608, 'mago', '3', 'Forma Gasosa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(609, 'mago', '3', 'Idiomas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(610, 'mago', '3', 'Glifo de Vigilância');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(611, 'mago', '3', 'Imagem Maior');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(612, 'mago', '3', 'Lentidão');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(613, 'mago', '3', 'Medo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(614, 'mago', '3', 'Padrão Hipnótico');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(615, 'mago', '3', 'Proteção contra Energia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(616, 'mago', '3', 'Montaria Fantasmagórica');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(617, 'mago', '3', 'Nevasca');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(618, 'mago', '3', 'Névoa Fétida');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(619, 'mago', '3', 'Pequena Cabana de Leomund');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(620, 'mago', '3', 'Piscar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(621, 'mago', '3', 'Relâmpago');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(622, 'mago', '3', 'Remover Maldição');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(623, 'mago', '3', 'Respirar Na Água');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(624, 'mago', '3', 'Toque Vampírico');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(625, 'mago', '3', 'Rogar Maldição');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(626, 'mago', '3', 'Velocidade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(627, 'mago', '3', 'Voo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(628, 'mago', '4', 'Arca Secreta de Leomund');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(629, 'mago', '4', 'Assassino Fantasmagórico');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(630, 'mago', '4', 'Banimento');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(631, 'mago', '4', 'Cão Fiel de Mordenkainen');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(632, 'mago', '4', 'Confusão');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(633, 'mago', '4', 'Conjurar Elementais Menores');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(634, 'mago', '4', 'Escudo de Fogo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(635, 'mago', '4', 'Invisibilidade Maior');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(636, 'mago', '4', 'Controlar a Água');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(637, 'mago', '4', 'Esfera Resiliente de Otiluke');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(638, 'mago', '4', 'Fabricar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(639, 'mago', '4', 'Malogro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(640, 'mago', '4', 'Metamorfose');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(641, 'mago', '4', 'Moldar Rochas');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(642, 'mago', '4', 'Localizar Criatura');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(643, 'mago', '4', 'Muralha de Fogo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(644, 'mago', '4', 'Olho Arcano');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(645, 'mago', '4', 'Pele de Pedra');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(646, 'mago', '4', 'Porta Dimensional');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(647, 'mago', '4', 'Santuário Particular de Mordenkainen');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(648, 'mago', '4', 'Tempestade de Gelo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(649, 'mago', '4', 'Terreno Alucinógeno');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(650, 'mago', '4', 'Tentáculos Negros de Evard');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(651, 'mago', '5', 'Âncora Planar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(652, 'mago', '5', 'Animar Objetos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(653, 'mago', '5', 'Círculo de Teletransporte');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(654, 'mago', '5', 'Cone de Frio');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(655, 'mago', '5', 'Conhecimento Lendário');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(656, 'mago', '5', 'Conjurar Elemental');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(657, 'mago', '5', 'Contato Extraplanar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(658, 'mago', '5', 'Criação');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(659, 'mago', '5', 'Criar Passagem');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(660, 'mago', '5', 'Despistar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(661, 'mago', '5', 'Dominar Pessoa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(662, 'mago', '5', 'Imobilizar Monstro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(663, 'mago', '5', 'Ligação Telepática de Rary');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(664, 'mago', '5', 'Mão de Bigby');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(665, 'mago', '5', 'Missão');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(666, 'mago', '5', 'Modificar Memória');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(667, 'mago', '5', 'Muralha de Energia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(668, 'mago', '5', 'Muralha de Pedra');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(669, 'mago', '5', 'Névoa Mortal');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(670, 'mago', '5', 'Similaridade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(671, 'mago', '5', 'Sonho');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(672, 'mago', '5', 'Telecinésia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(673, 'mago', '5', 'Vidência');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(674, 'mago', '6', 'Ataque Visual');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(675, 'mago', '6', 'Banquete dos Heróis');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(676, 'mago', '6', 'Círculo da Morte');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(677, 'mago', '6', 'Carne Para Pedra');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(678, 'mago', '6', 'Contingência');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(679, 'mago', '6', 'Corrente de Relâmpagos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(680, 'mago', '6', 'Criar Mortos-Vivos');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(681, 'mago', '6', 'Dança Irresistível de Otto');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(682, 'mago', '6', 'Desintegrar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(683, 'mago', '6', 'Esfera Congelante de Otiluke');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(684, 'mago', '6', 'Globo de Invulnerabilidade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(685, 'mago', '6', 'Invocação Instantânea de Drawmij');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(686, 'mago', '6', 'Ilusão Programada');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(687, 'mago', '6', 'Mover Terra');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(688, 'mago', '6', 'Portal Arcano');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(689, 'mago', '6', 'Proteger Fortaleza');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(690, 'mago', '6', 'Muralha de Gelo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(691, 'mago', '6', 'Raio Solar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(692, 'mago', '6', 'Visão da Verdade');

INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(693, 'mago', '6', 'Recipiente Arcano');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(694, 'mago', '6', 'Sugestão Em Massa');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(695, 'mago', '7', 'Bola de Fogo Controlável');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(696, 'mago', '7', 'Dedo da Morte');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(697, 'mago', '7', 'Espada de Mordenkainen');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(698, 'mago', '7', 'Forma Etérea');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(699, 'mago', '7', 'Inverter a Gravidade');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(700, 'mago', '7', 'Isolamento');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(701, 'mago', '7', 'Mansão Magnífica de Mordenkainen');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(702, 'mago', '7', 'Miragem');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(703, 'mago', '7', 'Prisão de Energia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(704, 'mago', '7', 'Projetar Imagem');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(705, 'mago', '7', 'Rajada Prismática');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(706, 'mago', '7', 'Simulacro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(707, 'mago', '7', 'Símbolo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(708, 'mago', '7', 'Teletransporte');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(709, 'mago', '7', 'Viagem Planar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(710, 'mago', '8', 'Antipatia/Simpatia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(711, 'mago', '8', 'Campo Antimagia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(712, 'mago', '8', 'Controlar o Clima');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(713, 'mago', '8', 'Clone');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(714, 'mago', '8', 'Dominar Monstro');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(715, 'mago', '8', 'Enfraquecer Intelecto');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(716, 'mago', '8', 'Explosão Solar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(717, 'mago', '8', 'Labirinto');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(718, 'mago', '8', 'Limpar a Mente');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(719, 'mago', '8', 'Nuvem Incendiária');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(721, 'mago', '8', 'Palavra de Poder Atordoar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(722, 'mago', '8', 'Semiplano');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(723, 'mago', '8', 'Telepatia');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(724, 'mago', '9', 'Alterar Forma');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(725, 'mago', '9', 'Aprisionamento');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(726, 'mago', '9', 'Chuva de Meteoros');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(727, 'mago', '9', 'Desejo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(728, 'mago', '9', 'Encarnação Fantasmagórica');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(729, 'mago', '9', 'Metamorfose Verdadeira');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(730, 'mago', '9', 'Muralha Prismática');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(731, 'mago', '9', 'Palavra de Poder Matar');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(732, 'mago', '9', 'Parar o Tempo');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(733, 'mago', '9', 'Portal');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(734, 'mago', '9', 'Projeção Astral');
INSERT INTO MAGIAS(ID, CLASSE, NIVEL, NOME) VALUES(735, 'mago', '9', 'Sexto Sentido');

INSERT INTO ESCOLAS(ID, ESCOLA, NIVEL, MAGIA) VALUES(1, 'abjuracao', '0', 'Resistência');
INSERT INTO ESCOLAS(ID, ESCOLA, NIVEL, MAGIA) VALUES(2, 'advinhacao', '0', 'Ataque Certeiro');
INSERT INTO ESCOLAS(ID, ESCOLA, NIVEL, MAGIA) VALUES(3, 'advinhacao', '0', 'Orientação');